### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by morkia** [kprokofi/light-weight-face-anti-spoofing#13]
I tested your model by converting it using model optimizer but it shows every image as spoof. Not sure what is the problem. I'm using OpenVINO 2021.2 on Windows 10 and python 3.7.

**Comment by morkia** [comment]
Never mind I found the issue. don't use the `--reverse_input_channels` when converting the model.

**Comment by kprokofi** [comment]
It's strange since the model receives RGB data. You can check conversion by running the conversion checker script. It checks Pytorch performance and OpenVINO after conversion.

**Comment by nhathoang0110** [comment]
I also have this problem and I use the same author default model on openvino 2021.2. I can't explain why?

**Comment by nhathoang0110** [comment]
![image](https://user-images.githubusercontent.com/55668910/119930448-a72c2b00-bfa9-11eb-8426-5fdf19460489.png)
this is my processing
